### ISSUE TITLE
Missing badge from the readme

### ISSUE THREAD

**Issue by NorbertFenk** [Vuncs/travis-oa-hw#1]
Hello :)

Could you please provide me a README.md with a badge about the build status?

Hint: sample project/README.md

**Comment by Vuncs** [comment]
Hi,

will be done after work hours... :)
I completely forgot it.

Thanks for the hint!

**Comment by Vuncs** [comment]
README.md with badge added.

**Comment by NorbertFenk** [comment]
Thank you! :)
